name: main

on:
  - push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Test and publish codecov
        uses: tests/fixtures/gendiff_test.py
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make coverage
          debug: true