name: main

on:
  - push
  - pull_request

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: install-dependencies
        run: pip install poetry && make install

      - name: check linter
        run: make lint

      - name: checking coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 624adb2e1242693bee7197b465fbadc3c9cfd58eaccdc1c10e52d5b1810ac05d
        with:
          coverageCommand: make test-coverage
          debug: true
