name: main

on:
  - push

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.9

    steps:
      - uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: install-dependencies
        run: pip install poetry && make install

      - name: check linter
        run: make lint

      - name: Test and publish codecov
        run: python3 tests/fixtures/gendiff_test.py
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make coverage
          debug: true
