name: main

on:
  - push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: gendiff_test@v4
      - name: Test and publish codecov
        uses: gendiff_test@v4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make coverage
          debug: true