name: main

on:
  - push
  - pull_request

jobs:
  push:
    jobs:
      - name: Test and publish codecov
        uses: tests/fixtures/gendiff_test
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make coverage
          debug: true