name: main

on:
  - push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test and publish codecov
        run: python3 tests/fixtures/gendiff_test.py
